### ISSUE TITLE
Error when adding tags to transaction

### ISSUE THREAD

**Issue by AlexVerrico** [jcwillox/up-bank-api#4]
When adding one or more tags to a transaction, the tags are added, but the response seems to cause an error in the module (see below).
Please let me know if there is any way I can assist in further diagnosing and/or fixing this issue.

Example code:
```python3
from upbankapi import Client

client = Client(token='TOKEN')

accounts = client.accounts()
spending_account = accounts[0]
transactions = spending_account.transactions(limit=1)
transaction_0 = transactions[0]
transaction_0.add_tags('test2', 'test3')
```

Exception:
```python3
Traceback (most recent call last):
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/Projects/348-UpBankExperiments/main.py", line 43, in <module>
    transaction_0.add_tags('test2', 'test3')
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/upbankapi/models/transactions.py", line 256, in add_tags
    return self._client.add_tags(self, *tags)
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/upbankapi/client/_sync.py", line 177, in add_tags
    return self._handle_add_tags(transaction, *tags)
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/upbankapi/client/base.py", line 189, in _handle_add_tags
    return self._handle_add_remove_tags("POST", transaction, *tags)
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/upbankapi/client/base.py", line 214, in _handle_add_remove_tags
    return self.api(
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/upbankapi/client/_sync.py", line 53, in api
    return self._handle_response(response.json(), response.status_code)
  File "/home/alex/Projects/348-UpBankExperiments/venv/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

After running the above code, the tags are added, (which can be verified with the following snippet) leading me to believe that it is just an issue parsing the response from the API.

Example code:
```python3
from upbankapi import Client

client = Client(token='TOKEN')

accounts = client.accounts()
spending_account = accounts[0]
transactions = spending_account.transactions(limit=1)
transaction_0 = transactions[0]
print(f'Transaction Tags: {transaction_0.tags}')

tags = client.tags(limit=5)
print(f'All Tags: {list(tags)}')
```

Output:
```text
Transaction Tags: [<Tag id='test2'>, <Tag id='test3'>]
All Tags: [<Tag id='test2'>, <Tag id='test3'>]
```

**Comment by jcwillox** [comment]
Ahh, I thought I had tested adding/removing tags and categories, but yeah there were a couple issues. In this instance, I was parsing the JSON response before checking for a 204 status (no response but successful).

Release [1.1.0](https://github.com/jcwillox/up-bank-api/releases/tag/1.1.0) should have fixed these issues.
